### ISSUE TITLE
Publicity - NEEDS YOUR HELP!

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/green#100]
Green should be listed next to py.test in public lists of python test frameworks!

If people have a hard time finding out about green, they won't use green!  Life will be so much slower and less colorful for them.  Don't let that happen!

LET ME KNOW about other places that ought to link to green:

- [x] https://github.com/vinta/awesome-python/pull/335
- [ ] Move the origin story from the README to a medium post, and link it on reddit
- [ ] [Python unittest module documentation](https://docs.python.org/3/library/unittest.html)
- [ ] [Unit Testing Tools Page](https://wiki.python.org/moin/PythonTestingToolsTaxonomy) on the python wiki
- [ ] Make green available through [the conda installer](http://conda.pydata.org/docs/)

**Comment by Ogaday** [comment]
I only came across green recently, and I can't remember how, unfortunately. Turn the origin section of your readme into an article (it wouldn't take much work because it's well written), post it on your blog, on medium, then link it on reddit (/r/python), twitter and other social network platforms. I think content is received better in that form than a simple advertisement.

**Comment by Ogaday** [comment]
I'm not sure you have enough lines of code, but you could enter [this comptetion](http://www.yegor256.com/2015/10/17/award-2016.html) for the publicity, money and free feedback. I found the blog posts pretty interesting as well, if a little vehement!

**Comment by CleanCut** [comment]
@Ogaday That competition looks awesome.  Unfortunately, I'm not even halfway to the 10,000 lines of code minimum.

Thanks for the suggestion about medium and reddit.  That's what I've been doing for major/minor releases (not dot releases).  But going back and turning the origin story into a medium post is a good idea.  I wasn't on medium at the time I originally wrote that.

**Comment by Ogaday** [comment]
@CleanCut Good job on the getting the pull request accepted. You should look to get on the [unittest documentation page](https://docs.python.org/3/library/unittest.html). Pytest and nose are there. Also linked are the testing page on the [python wiki](https://wiki.python.org/moin/PythonTestingToolsTaxonomy) and the [Testing in Python Mailing List](http://lists.idyll.org/listinfo/testing-in-python). I don't know how you'd get on those different pages, but it's a start.

**Comment by Ogaday** [comment]
@CleanCut Have you come across the Anaconda distribution and specifically the environment/package manager Conda? Not entirely sure what it entails, but distributing green via conda/binstar might make it more accessible to scientific users in particular.

**Comment by CleanCut** [comment]
@Ogaday Thanks!  I added those all to the list.

**Comment by Ogaday** [comment]
[Pytontesting.net](http://pythontesting.net/) who delivered a fantastic [article](http://pythontesting.net/strategy/why-most-unit-testing-is-waste/) would look like a good place to get coverage. Perhaps ask for a review, in the same way the author [has reviewed nose and pytest](http://pythontesting.net/podcast/pytest-vs-unittest-vs-nose-pt002/).

**Comment by CleanCut** [comment]
I actually contacted the guy behind pythontesting.net last August.  Here's a snippet from his reply email where he declined to look at green :-(

    Those features might be awesome, but they aren't useful to me.
    I can't run tests concurrently against one system anyway.
    And I don't actually watch the test run, I parse the report and push it to a web site that graphs the results for each test run.

**Comment by nMustaki** [comment]
There's a podcast I like, [ talkpythontome] (http://talkpython.fm), the author may be happy to interview you ?

**Comment by CleanCut** [comment]
My publicity ambitions have been sufficiently satisfied.
