### ISSUE TITLE
Test generators a la nose

### ISSUE THREAD

**Issue by Ogaday** [CleanCut/green#101]
See here: https://nose.readthedocs.org/en/latest/writing_tests.html#test-generators

When using nose I found test generators incredibly useful for avoiding duplicate code. What would it take to implement that sort of functionality in green? I'd be happy to have a go at implementing it myself if someone could talk me through it.

**Comment by Ogaday** [comment]
Is this actually solved by the support for nose-paramterized? That looks like the same sort of idea.

**Comment by CleanCut** [comment]
Yes, that's what the [nose-parameterized](https://github.com/CleanCut/green#nose-parameterized) stuff is.  Hopefully that works for you.

**Comment by Ogaday** [comment]
Ok, I'll have a play with it. This issue can be closed then?

**Comment by CleanCut** [comment]
Yep.
