### ISSUE TITLE
Adding Xunit/Junit Xml report

### ISSUE THREAD

**Issue by JayZar21** [CleanCut/green#104]
It is a standard feature which is needed for Jenking and CI integration.
Please consider it.
Thanks.

**Comment by CleanCut** [comment]
This might be a duplicate of #34 

I hope to do some feature to enable integration with Jenkins.

**Comment by carldunham** [comment]
A nice-to-have for us CircleCI users also

**Comment by CleanCut** [comment]
If someone would like to give implementing that type of output a try, I would be happy to point them in the right direction and review PR's.

**Comment by CleanCut** [comment]
✅ `-j/--junit-report` shipped in 2.15.0, which was just released.  Thanks to @fchauvel for contributing this feature! 🎉
