### ISSUE TITLE
Limited Python 2.6 support using unittest2

### ISSUE THREAD

**Issue by jayvdb** [CleanCut/green#106]
With a little hacking, I've got the tests mostly passing on Python 2.6 with unittest2

https://github.com/jayvdb/green/commits/py26

https://travis-ci.org/jayvdb/green/builds/93819881

If there is a chance it could be merged, I would be happy to clean it up so that there is no chance of impact on Python 2.7+ , and all tests pass or are skipped.

I appreciate "supporting" Python 2.6 may not be desirable long term, but it would help if there was one version on pypi marked as Python 2.6 compatible, so that installing 'green' always works, and the older version of green is selected on Python 2.6.

Python 2.6 could be marked as an 'allowed failure' in travis, so it is a 'second tier' / 'best effort' platform.

**Comment by CleanCut** [comment]
Sorry for the huge delay.

I looked into it, and I found that I am simply not willing to let the Python 2.6 support changes into the tree.

However, I would be perfectly happy to update the ReadMe to link to an official "green26" fork or something like that if you wanted to maintain such a thing.

**Comment by jayvdb** [comment]
Thanks for thinking about it, but also for giving the green light for a green26 fork. ;-)
Im not sure I'm super motivated to do it, as we've pretty much gone ahead with py.test since it has py26 support, and we have it doing most of what we need now.

**Comment by CleanCut** [comment]
I don't blame you.  I know just exactly how massive an effort it is to get something like green working (and maintained) on a new version of python.
