### ISSUE TITLE
Does not run on debian

### ISSUE THREAD

**Issue by omnidan** [CleanCut/green#110]
After installing `green` with `sudo pip3 install green` and running `green`, I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/green", line 9, in <module>
    load_entry_point('green==2.2.0', 'console_scripts', 'green')()
  File "/usr/local/lib/python3.4/dist-packages/green/cmdline.py", line 29, in main
    from green.loader import loadTargets
  File "/usr/local/lib/python3.4/dist-packages/green/loader.py", line 13, in <module>
    from green.output import debug
  File "/usr/local/lib/python3.4/dist-packages/green/output.py", line 2, in <module>
    from colorama.ansi import Cursor
ImportError: cannot import name 'Cursor'
```

**Comment by omnidan** [comment]
Installing it via `sudo easy_install green` fixed the issue.

**Comment by CleanCut** [comment]
Weird.  Why would an import from `colorama` fail based on which package manager installed it?  ((shrugs and shakes head sadly))

**Comment by jayvdb** [comment]
Wrong version of colorama?

**Comment by CleanCut** [comment]
That could cause the import fail, but `sudo easy_install green` shouldn't alter the version of colorama from what pip had already installed.

Perhaps his `easy_install` was from a different version of python, and his 3.4 had a very old or very new version of colarama?  That could do it.

**Comment by omnidan** [comment]
I think colorama might've been installed by `easy_install` and then I installed `green` with `pip`. It definitely sounds like a version mismatch.
