### ISSUE TITLE
psycopg2 closed the connection unexpectedly (Django1.9/python3.5)

### ISSUE THREAD

**Issue by marshallds** [CleanCut/green#113]
Works great as long as I only run a single file.  When I split my tests.py into tests/test_*.py and run the suite I get the following on the first test:
```
  File "/home/marshallds/Projects/concerto/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

After that the rest of the tests fail due to the database connection being in a bad state.  If I use the default django test runner it works fine.

Let me know if I can provide more detail.  Thanks!

**Comment by CleanCut** [comment]
What happens if you add a `.green` config file to your home directory with `processes=1` in it?

**Comment by CleanCut** [comment]
Apparently there are no more problems with this at the moment.  Feel free to reopen this issue if you need to.
