### ISSUE TITLE
Per project configuration?

### ISSUE THREAD

**Issue by MinchinWeb** [CleanCut/green#116]
Does `green` currently support per project configuration files? If not, would it be as simple as adding the current directory to where `green` searches for configuration files?

**Comment by CleanCut** [comment]
No, we don't.

Essentially yes, it should be _almost_ that easy.  We'll also have to update the docs and write some tests too.

**Comment by MinchinWeb** [comment]
if you're considering more configuration options, would storing settings in files such as `setup.cfg` or `.editorconfig`, which might already exist, be good options to consider too?

**Comment by CleanCut** [comment]
I'm not opposed to it.  But I don't use those files, so it'd need someone who does to do the work.  Should be slightly more work since you'll need to deal with a special `[green]` config section or something like that I imagine.

**Comment by CleanCut** [comment]
Support for this is in the just-released 2.8.0 version.
