### ISSUE TITLE
Add version information to module

### ISSUE THREAD

**Issue by mairsbw** [CleanCut/green#128]
It's helpful when checking dependencies programmatically or for a developer to be able to retrieve version information from the modules `__version__` attribute (see [PEP396](https://www.python.org/dev/peps/pep-0396/)).

Our use case is a `check_dependencies.py` script that the developer can run to verify they have all necessary packages installed and that they're the correct version.

**Comment by CleanCut** [comment]
Excellent idea.  Especially since I already did the hard work setting `green.version.__version__`, so it's only a one-line fix.

**Comment by CleanCut** [comment]
Included in 2.5.1 (just released).
