### ISSUE TITLE
Such is not supported?

### ISSUE THREAD

**Issue by zeitos** [CleanCut/green#130]
Hi, 
   I'm running the example from
[such](http://nose2.readthedocs.io/en/latest/such_dsl.html) and it seems like it's not working with green:

![image](https://cloud.githubusercontent.com/assets/1010275/16876855/100fc08a-4a7c-11e6-9503-13e5d38bacfc.png)

**Comment by CleanCut** [comment]
Correct.  "such" is not supported by green.
