### ISSUE TITLE
dont support unittest.skipIf

### ISSUE THREAD

**Issue by johnChnia** [CleanCut/green#144]
version:   2.7.2
os : mac

code；

```python
from __future__ import unicode_literals
import sys
import unittest


class TestStates(unittest.TestCase):

    def test0Pass(self):
        """
        This test will print output to stdout, and then pass.
        """
        print("Sunshine and daisies")

    @unittest.skipIf(True, "I am skipIf++")
    def test1Fail(self):
        """
        This test will print output to stderr, and then fail an assertion.
        """
        sys.stderr.write("Doom and gloom.\n")
        self.assertTrue(False)

    @unittest.skipUnless(False,"I am skipUnless")
    def test2Error(self):
        """
        An Exception will be raised (and not caught) while running this test.
        """
        raise Exception

    @unittest.skip("This is the 'reason' portion of the skipped test.")
    def test3Skip(self):
        """
        This test will be skipped.
        """
        pass

    @unittest.expectedFailure
    def test4ExpectedFailure(self):
        """
        This test will fail, but we expect it to.
        """
        self.assertEqual(True, False)

    @unittest.expectedFailure
    def test5UnexpectedPass(self):
        """
        This test will pass, but we expected it to fail!
        """
        pass
```

when i run this code in pycharm, the result like thsi:

![image](https://cloud.githubusercontent.com/assets/12187260/20590156/6bf4bb42-b25c-11e6-9cda-f688839d3251.png)

but when i run this code in green:

![image](https://cloud.githubusercontent.com/assets/12187260/20590175/89ad85b0-b25c-11e6-9838-bc9694b7f1d9.png)

I think this is a bug

**Comment by CleanCut** [comment]
What do you think is a bug?

**Comment by CleanCut** [comment]
I'm sorry, but it works fine for me on my Mac using Python 2.7.12, Python 3.5.2, or PyPy 5.6.

I can't reproduce your problem.  Perhaps it is because you are using Python 2.7.2 (which is very old).  Have you tried updating to macOS Sierra?

![screen shot 2017-02-14 at 5 01 37 pm](https://cloud.githubusercontent.com/assets/5838512/22955042/53823a74-f2d7-11e6-927a-ecdcd2fd23d7.png)

**Comment by johnChnia** [comment]
i am sorry, i will try right now
