### ISSUE TITLE
osx virtualenv of python3, green running python2.7?

### ISSUE THREAD

**Issue by Thetoxicarcade** [CleanCut/green#147]
I installed green in a virtualenv on osx, but when running it, it used python2.7.

is there a way to force it to use the python version I need it to?

**Comment by dougthor42** [comment]
Can you provide more details on what exactly you did? Perhaps the commands you ran?

**Comment by Thetoxicarcade** [comment]
@dougthor42 Sorry about that... didn't notice the notification. I'll have to have them pull out their mac.

**Comment by CleanCut** [comment]
In general, the answer is simply "install green using pip inside the virtualenv".

Alternatively, you can run "path/to/virtualenv/python -m green"
