### ISSUE TITLE
Thank You! - Python Testing with Green - State of the Me

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/green#157]
@rolobio @tbarron @svisser @smspillaz @hindman @miohtama @e3krisztian @jayvdb @nMustaki @thijstriemstra @skeggse @gurnec @MinchinWeb @althonos @anomitra @dtan3847 

THANK YOU!

Each of you that I have mentioned on this issue has contributed to Green via a pull request that has been accepted and merged.

As a thanks, I would like to provide each of you with a personal 10-use coupon for a free subscription to the [Python Testing with Green](https://github.com/CleanCut/green/blob/master/PythonTestingWithGreen.md) course I am creating on Udemy (it's available already, though it's not quite finished -- release early, release often!).

I know you're probably all python-unittest-mock-green experts already, but maybe your friend or coworker would learn something from the course. :-)

For your personal code, I just need to know which email address to send it to.  You can either email me at nathan.stocks@gmail.com (tell me your Github username if it's not obvious!) and I'll reply with your code, or if you're less squeamish you can just reply with your email right here on this issue.

DOES THIS CHANGE ANYTHING?

No, not really. I'm not going commercial or anything silly like that. I would like to spend *more* time on Green than the few hours a week I am currently spending, but I'm already working 2 jobs and supporting a family which means spare time is pretty hard to come by.  My 2nd job at [Agile Perception](https://agileperception.com) in addition to being a fledgling attempt at an Indie Game company is essentially a consulting/contracting side-business for software development.  So if I can make working on Green a _part_ of that business, then I can actually spend _more_ time on Green during my 2nd-job-time.  Then maybe I can get some of those bigger enhancement requests implemented.

I'd love to transition to my full-time job supporting working-on-open-source someday.  If you have any _good_ tips on how to achieve that, I'm all ears. ;-)  So far my best idea seems to be creating educational courses.  (Of course, we'll have to see if I can manage to enroll any paying customers). I have spent most of what little free time I do have with [Rust](https://www.rust-lang.org/en-US/) lately.  I just had my first two pull requests accepted to that project (bug fixes to their internal build system), and I have begun a Udemy Rust course as well.  It's like the Python of systems-level programming languages!  Lots of fun!

So that's what's going on with me.  What's going with you?

**Comment by thijstriemstra** [comment]
Unsubscribing.

**Comment by CleanCut** [comment]
Keeping track of stuff:

althonos - Done!
anomitra -
dtan3847 
e3krisztian - 
gurnec -
hindman -
jayvdb - Done!
MinchinWeb - 
miohatama -
nMustaki - 
rolobio -
skeggse -
smspillaz - Done!
svisser -
tbarron -
thijstriemstra - Apparently not interested.
-

**Comment by anomitra** [comment]
Hi @CleanCut, you can mail me here: anomitra1993@gmail.com.

All the best with the course!

**Comment by CleanCut** [comment]
The course is starting to get a little traction!  I have a couple dozen students, and I have nearly finished the advanced section.

I'm going to go ahead and "close this issue", but those of you who have not yet responded are welcome to contact me sometime if you decide you would like your free subscription coupon.

**Comment by CleanCut** [comment]
@dougthor42 I somehow missed you on the original post.  Fixed!

**Comment by CleanCut** [comment]
@VladV Thanks for you PR! If you would like a 10-use coupon for a free subscription (see the top post for details), just send me your email address via some means and I'll send it over to you.
