### ISSUE TITLE
setup.py runner

### ISSUE THREAD

**Issue by jayvdb** [CleanCut/green#158]
A lower impact version of https://github.com/CleanCut/green/issues/87 is to create a `setup.py` runner like https://github.com/pytest-dev/pytest-runner, so that green can be invoked using the tests as defined in `setup.py`, like:

`python2 setup.py green`

**Comment by mmaiasouto** [comment]
_blank

**Comment by CleanCut** [comment]
@mmaiasouto ?

**Comment by CleanCut** [comment]
Feature added in version 2.10.0, just released.
