### ISSUE TITLE
coverage does not work for files that are out of site

### ISSUE THREAD

**Issue by althonos** [CleanCut/green#164]
Coverage does not reach files that are installed. This is probably a missing configuration value for `coverage` in `green/process.py`.

Can be reproduced with `green green.test -r`

**Comment by CleanCut** [comment]
Hehe, fooled you. ;-)

It works alright, we just assume most people don't want to see green and python library files in their coverage reports.

Try running `green green.test -r --clear-omit`

**Comment by althonos** [comment]
@CleanCut : I figured that later haha, sorry ! 😸
