### ISSUE TITLE
Can't run specific tests targeting Blender

### ISSUE THREAD

**Issue by Coburn37** [CleanCut/green#170]
I'm trying to run suite of tests that target [Blender](blender.org) and I get the following error.

![image](https://user-images.githubusercontent.com/6759176/31367959-a4dac720-ad48-11e7-983a-2bc037bac562.png)
```
C:\Users\XXXXXX\Dropbox\Dev\RLD_Toolkit>C:\python35\python -m green tests.test_utils
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
E

Error in .tests.test_utils
TypeError: Test loader returned an un-runnable object.  Is "tests.test_utils" importable from your current location?  Maybe you forgot an __init__.py in your directory?  Unrunnable object looks like: None of type <class 'NoneType'> with dir ['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

Ran 1 test in 0.987s

FAILED (errors=1)
Error: Not freed memory blocks: 8, total unfreed memory 0.008392 MB

```

I have also included my file heirarchy:

![image](https://user-images.githubusercontent.com/6759176/31367980-c90df84c-ad48-11e7-8a1b-2293a9794172.png)

To give a bit of background on how Blender in Python works, Blender is compiled into a `bpy.pyd` file imported through `import bpy` whereby a headless Blender process will be spun up and the root python object is accessible in the current python environment. I see that this might be problematic according to https://github.com/CleanCut/green/issues/163.

Upon creating a minimal test case, the failure does indeed hinge on `import bpy`. Removing it will cause the tests that don't rely on Blender (only a select few) to be found and run properly.

I'm only posting this because while it doesn't work in `green`, I just tried and it does work in `pytest` (see below). From my experience with Blender as a Python module, I assume that Blender does some really weird import machinery rewriting to handle all its internal stuff but ultimately I'm not sure why `pytest` works and `green` does not.

If there is more troubleshooting information I can provide, let me know. I wasn't really sure where to go from here.

Pytest:

![image](https://user-images.githubusercontent.com/6759176/31368261-ab8b674e-ad4a-11e7-9b60-970780e4564d.png)

**Comment by CleanCut** [comment]
Where is the `bpy.pyd` file actually located on disk?

**Comment by Coburn37** [comment]
It's a very weird module in that `bpy.pyd` lives in `C:\python35\Lib\site-packages` and then loads all of it's supporting Python resources from `C:\python35\2.79` where `2.79` is the Blender version (this is all laid out in the Blender build process though).

Calling `import bpy` in an interactive python session will load the module `bpy` and also allow for other Blender modules to load like `mathutils`. If you try `import mathutils` before `import bpy` it won't work (so it's definitely doing some weird stuff behind the scenes).

**Comment by CleanCut** [comment]
You ran pytest on the whole project, but green on just one test file.  Might as well try `python -m green` and see if that behaves any differently.

Other than that, I'm stumped.  I don't use Blender or Windows, and without being able to poke around I'm not sure there's anything else I can do.

Any Windows experts out there want to give this one a shot?

**Comment by CleanCut** [comment]
Or blender experts?

**Comment by Coburn37** [comment]
It behaves the same and gives similar output for each file if I just run `python -m green` or `green`. I'll report back with any more information but I'm as stumped as you are.

In the meantime, it looks like if anything it's going to be something in [`bpy_interface.c`](https://github.com/dfelinto/blender/blob/master/source/blender/python/intern/bpy_interface.c) or [`bpy_internal_import.c`](https://github.com/dfelinto/blender/blob/master/source/blender/python/generic/bpy_internal_import.c) (the second one monkey-patches Python's import function apparently) and is then probably a Blender problem but I'll let you know

**Comment by CleanCut** [comment]
You're probably right, so I'm going to go ahead and close this issue.  But if you find some new information that would point to a way that we could fix it in green, feel free to reopen.
