### ISSUE TITLE
Django 2.x support

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/green#193]
It's time to make sure green works (well) with Django 2.x.

**Comment by Oxicode** [comment]
+1

**Comment by vanities** [comment]
Just wanting to make sure, green doesn't support django 2 right?

getting this when trying in docker: `docker-compose  run --rm test green`
```
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Of course, the apps aren't loaded, what kind of work would have to be done to load the apps for green?

**Comment by CleanCut** [comment]
@vanities Correct, green does not support Django 2 yet.

I haven't looked at it yet.  It's entirely possible that supporting Django 2 is very easy. Django 1 support wasn't particularly hard.

**Comment by CleanCut** [comment]
I took a look at Django 2 today, specifically version 2.1.5 on Python 3.7.2.

Everything worked for me!

@vanities Are you using a functioning django app, or trying out a brand new one?  If a new one, perhaps you need to [install your app](https://docs.djangoproject.com/en/2.1/intro/tutorial02/#activating-models)?  That's just a shot in the dark. All I know about Django is what I see in the tutorial when I run through it to make sure Green will work.
