### ISSUE TITLE
Django compatibility

### ISSUE THREAD

**Issue by hjwp** [CleanCut/green#21]
The Django test runner does all sorts of magic to set up a test database.  For green to work with Django, it would have to hook into all that voodoo somehow.

Here's a minimal django project you can use for tests:  https://github.com/hjwp/Minimal-Django-project-with-model-test

to run green, use:

```
DJANGO_SETTINGS_MODULE=myproj.settings green
```

**Comment by pkrefta** [comment]
@CleanCut Thanks for django. I don't want to open another to ask simple question - how can I set verbosity for DjangoRunner ? 😄
