### ISSUE TITLE
green might hang on async tests

### ISSUE THREAD

**Issue by WolfgangFahl** [CleanCut/green#263]
https://github.com/justpy-org/justpy tries using green for tests
in the scripts directory i tried using green

i had to uncomment it and replace with python -m unittest
```bash
modulewise_test() {
  for testmodule in tests/test*.py
  do
    echo "testing $testmodule ..."
    #green $testmodule
    python -m unittest $testmodule
  done
}
````
since
```bash
 green tests/test_demostarter.py 
```
simply hangs while
```bash
python -m unittest tests/test_demostarter.py 
Starting test testDemoStarter, debug=False ...
found 38 justpy demo python modules
starting   1:examples.tutorial.page_events.loading_page_no_stagger:loading_page_no_stagger:loading_page_no_stagger  ...
```
works just fine ...

**Comment by CleanCut** [comment]
green's use of subprocesses is unlikely to play well with async. You can restrict green to a single subprocess with `-s 1` or `--processes 1` and it _might_ work.

**Comment by WolfgangFahl** [comment]
@CleanCut  Thx - actually works better and very helpful to know

**Comment by CleanCut** [comment]
Great! Glad to hear it. 😄
