### ISSUE TITLE
Please add me to the project as a maintainer

### ISSUE THREAD

**Issue by IanFoertsch-clumio** [CleanCut/green#282]
@CleanCut I work closely with @sodul, is it possible to be added as a maintainer to assist in the release process?

I understand that the release process is currently bottlenecked by @sodul being the most active maintainer. Adding me as a maintainer would allow me to assist in the release process & ensure the project is able to release new features.

Please let me know if you have any questions.

**Comment by sodul** [comment]
@CleanCut I work with @IanFoertsch-clumio at Clumio where we use green daily. He is a solid Python developer and will help review the PRs.

**Comment by sodul** [comment]
@IanFoertsch-clumio was able to approve a PR. Thanks @CleanCut!
