### ISSUE TITLE
subunit support

### ISSUE THREAD

**Issue by meejah** [CleanCut/green#34]
I've just started playing with Green and it works really well so far. However, I'd like to use it in automated tools, and I've had good success with subunit for this (reporting up to buildbot, for example).

Supporting subunit via a plugin or directly would be great!

Alternatively, some sort of structured output option (junit XML? json?) would be nice instead (or as well).

**Comment by Julian** [comment]
You can (easily) downconvert subunit to junit XML -- and it's fairly easy to generate subunit if you have similar support for reporters as trial does (I haven't checked, is there?) Regardless, if you have subunit support you'd be able to use green in Jenkins.

**Comment by CleanCut** [comment]
@Julian Green does not have a plugin interface like trial reporters, and I have no plans to add one at the moment.

I do still think it would be good to add features to green such as subunit support, though.  Real life just keeps delaying me from getting to it.  Patches welcome if someone beats me to it!

**Comment by CleanCut** [comment]
@meejah Green now has a `-j/--junit-report` feature contributed in #204.  I'm going to close this issue guessing that this fills your need, but feel free to open the issue back up if it doesn't and explain why.
