### ISSUE TITLE
Make green work with nose_parameterized

### ISSUE THREAD

**Issue by smspillaz** [CleanCut/green#39]
Green doesn't work with `nose_parameterized` since it executes tests that `nose_parameterized` [marks](https://github.com/wolever/nose-parameterized/blob/master/nose_parameterized/parameterized.py#L232) as disabled using the nose-specific [`__test__`](https://github.com/nose-devs/nose/blob/master/nose/tools/nontrivial.py#L140) attribute

This attribute is easy to detect, so we should prune any tests that have it set.

**Comment by smspillaz** [comment]
Incidentally this also enables parameterised tests #38

**Comment by CleanCut** [comment]
Included in green 1.8.0, released today.
