### ISSUE TITLE
Does green support different file naming patterns?

### ISSUE THREAD

**Issue by hindman** [CleanCut/green#41]
At various points in `loader.py`, it looks like green intends to support the idea of a `file_pattern`. But I don't see any command-line options to control this behavior. Also, I don't think that the value of `file_pattern` is actually being passed through the call stack down to the underlying `discover()` function. Perhaps I'm overlooking something.

Anyway, green looks like a great project and I'm eager to try it out (frustrated with nose, pytest, and unittest). But on my team we follow a `*_tests.py` naming convention, so I've been unable to get out of the starting gate.

**Comment by CleanCut** [comment]
You are correct, I intended to support it and stubbed in support for it, but then no one appeared to ever need it in the real world, so I never ended hooking it up and making sure it worked.  Python's built-in unittest module discovery is hard-coded to discover files named `tests*.py`, so most of the world has followed suit.

If you would like to take a stab at hooking it up, I welcome pull requests.

Or if you would like to send me a stripped-down tarball/zipfile of an example project that follows the conventions you're using, I can see if I can hook it up sometime this week (if my design was forward-looking enough).

**Comment by hindman** [comment]
@CleanCut Created a pull request. It might not have everything that's needed, but it at least gets the ball rolling.

**Comment by CleanCut** [comment]
@hindman I can't find anything to fix with it.  Good job!  I didn't realize it was quite that close to being implemented already.  It'll be released in version 1.8.0 as soon as you let me know how you want me to refer to you (or not) in the changelog.

**Comment by CleanCut** [comment]
Included in green 1.8.0, released today.
