### ISSUE TITLE
Options set via config file are disrespected

### ISSUE THREAD

**Issue by hindman** [CleanCut/green#56]
Options set via a config file are no longer working for me. Here's a simple example:

    $ cat ~/.green
    verbose = 2

    $ green
    .....
    Ran 5 tests in 0.001s
    OK (passes=5)

I observe the same problem with other options in my config file (eg, `file_pattern`). They aren't being picked up at all.

When I checkout to v1.71, the example above works as expected, but not in v1.80 and beyond.

**Comment by CleanCut** [comment]
Included in 1.9.1 released just now.
