### ISSUE TITLE
Green 1.9.1 - would appear that --allow-stdout is broken

### ISSUE THREAD

**Issue by xdrjbotts** [CleanCut/green#58]
Hi -

Very much like green - thanks for providing it.  It would appear that the -a or --allow-stdout option is not working - stdout is still captured with the argument.  Have tested with

Green 1.9.1, Python 3.4.3
Green 1.9.1, Python 2.7.9

If I change the value of allow_stdout to True in default_args in config.py:47 - then stdout is not captured - so it would appear that there is some issue in parsing the arguments to green.  Haven't dug down to that part of the code yet.

Thanks, Jim

**Comment by CleanCut** [comment]
Lets find it and fix it.  Can you show me your actual config file, the command-line arguments you were using, and exactly how you were getting stuff to stdout (print statement?)?

**Comment by CleanCut** [comment]
Found it!  Fixed it.  I just released 1.9.2 that includes the fix.  It was a regression that affected only that one option's implementation.
