### ISSUE TITLE
Support AppVeyor's PowerShell

### ISSUE THREAD

**Issue by dougthor42** [CleanCut/green#67]
Running green in AppVeyor CI does not color results.

However, I think this may be an AppVeyor issue, as I can run green in Windows PowerShell myself and get at least some form of coloring (other issues, such as IT permissions here at work) are preventing me from really testing green + PowerShell thoroughly.

I figured I'd record this issue here even if it's out of your control.

**Comment by dougthor42** [comment]
Confirmed, green works just fine in Powershell:
![green powershell](https://cloud.githubusercontent.com/assets/5386897/8290951/154cb324-18db-11e5-9f8c-4bc5a1d574f8.jpg)

(though the blue is a little hard to read).

So it must just be an AppVeyor thing, or perhaps how they mimic powershell in the browser.

**Comment by CleanCut** [comment]
Apparently AppVeyor started supporting color ... but it still doesn't work.

I've added a comment to their discussion of color support asking for help:

http://help.appveyor.com/discussions/suggestions/197-support-ansi-color-codes

**Comment by CleanCut** [comment]
Fixed.  You can preview it in the `process-overhaul` branch or wait until the next release comes out.  Here's an example just for fun: https://ci.appveyor.com/project/CleanCut/green/build/job/4sn6gm4awraogqxb
