### ISSUE TITLE
Add screenshots to readme.

### ISSUE THREAD

**Issue by calebmeyer** [CleanCut/green#78]
This test runner is labeled colorful by the description, yet shows no colors in the readme.

Could we add screenshots, similar to the readme for [httpie](https://github.com/jkbrzt/httpie)?

**Comment by CleanCut** [comment]
(Sorry for the delay, I was on vacation)

That's a great suggestion!  I'll see if I can get to that today!  Thanks for linking to a good example.

**Comment by CleanCut** [comment]
Done!
