### ISSUE TITLE
Not reading config options from file

### ISSUE THREAD

**Issue by tume** [CleanCut/green#79]
Using green as django testrunner and config file seems to be the only way to actually pass any options to green. 

I have created $HOME/.green file but no affect no matter what options I put there... also tried setting GREEN_CONFIG env variable but also no affect.

Using Green 2.0.1, Python 3.4.2

**Comment by CleanCut** [comment]
Okay, so you're saying that you're using green in a django project, and neither `$HOME/.green` or `GREEN_CONFIG` seem to get your options through to it, right?

What is the content of your `.green` file?  Are you using the command-line way to specify green, the setup.py way, or some other way?  (see https://github.com/CleanCut/green#django )

**Comment by tume** [comment]
`$HOME/.green`:
verbose       = 3
logging       = True
debug         = 1

I was first interested just specifying processes count and allow-stdout but thought that these would be easier to test. 

I also downgraded to green 1.7.1 and with that version it seems to read these correctly or at least I get more verbose output.

In my django config: `TEST_RUNNER="green.djangorunner.DjangoRunner"
`

**Comment by CleanCut** [comment]
Sorry for the slow response.  Life has been very crazy for me.  There was definitely a bug causing the `DjangoRunner` to ignore all config files.  The bug is fixed in the upcoming `2.0.5` release.
