### ISSUE TITLE
How to run coverage with django?

### ISSUE THREAD

**Issue by enkitosh** [CleanCut/green#82]
Hi I fail to see how I would run coverage on top of having green as TEST_RUNNER in django.

    python manage.py test --run-coverage

manage.py: error: no such option: --run-coverage

of course because --run-coverage is not an option of manage.py. But how do I combine this?
I've tried putting this into my ~/.green config

    run-coverage = True

but it does not change anything. Hoping I haven't missed something obvious from the docs but how would you pass an option to green while running under django?

thank you

**Comment by CleanCut** [comment]
There was a bug preventing the DjangoRunner from reading config files.  It has been fixed in the upcoming 2.0.5 release.

**Comment by enkitosh** [comment]
Ok nice, good to know. Thank you CleanCut :+1:

**Comment by CleanCut** [comment]
No problem!  `2.0.5` and `2.0.6` were released yesterday.
