### ISSUE TITLE
Default value for --processes flag is not 1 as told in help

### ISSUE THREAD

**Issue by mindbrave** [CleanCut/green#83]
It's instead multithreading.cpu_count().

**Comment by CleanCut** [comment]
Thanks for finding this!  The fix to the help text will go out in the next release.

**Comment by CleanCut** [comment]
The change was included in `2.0.7`, which was just released.

**Comment by mindbrave** [comment]
Thanks, but I would consider setting default as `1`. I lost some time debugging my integration tests which were running concurrently and flushing db at the worst time. I wasn't aware that tests can run in parallel by default :)

**Comment by krisztianfekete** [comment]
I am another user and I like it running tests concurrently by default, because I can spare remembering  and typing `-s 0` all the time.

@mindbrave  Would it helped you debugging if the number of concurrent processes was displayed?

Something like this:
```
$ green
.......................................................................

Ran 71 tests in 3.118s using 4 processes

OK (passes=71)
```

New stuff here is ` using 4 processes`

**Comment by mindbrave** [comment]
@krisztianfekete Yes, I think so. Green is the first test runner I met that runs things concurrently by default.

**Comment by CleanCut** [comment]
@krisztianfekete That's an excellent idea.  I think I'll create an issue for that just so that I remember to actually do it.
