### ISSUE TITLE
Add output mode to show test method name in addition to docstring

### ISSUE THREAD

**Issue by jayvdb** [CleanCut/green#94]
unittest shows test method name and docstring.
nose only shows the docstring, if it exists, or the method name if it doesnt have a docstring.

https://github.com/wikimedia/pywikibot-core is searching for an advanced test runner like nose (and I am very impressed with `green` so far), but we'd like the output to include the test method names, so that it is easy to rerun an individual test method using its dotted.name.

The following layout would be ideal
```
module
  class
    method1: docstring
    method2: docstring
```

See https://phabricator.wikimedia.org/T115313 for our task related to this.

**Comment by CleanCut** [comment]
I absolutely agree.  It's part of #30.
