### ISSUE TITLE
'Failed to create process'

### ISSUE THREAD

**Issue by MinchinWeb** [CleanCut/green#98]
Using Python 3.5.0 x64 on Windows 10 with Green 2.1.2.

Try to run any `green` command, and it fails and displays the message `Failed to create process`.

The issue is present on Green 2.1.1 and 2.1.0, but not Green 2.0.7 (which works fine).

**Comment by CleanCut** [comment]
(Sigh) I don't even have access to Windows 10. :-(

**Comment by MinchinWeb** [comment]
Well, maybe I can help more. I can confirm that this isn't an issue with Python 3.4.3. I can also confirm that if I clone the repo and run `python setup.py install`, `green` installs and runs fine on Python 3.5. This would point to the `.tar.gz` file on PyPI; something in the packaging or distribution. Is it time to move to wheels? If you can upload one here, I can try installing it to see if that fixes it.

**Comment by CleanCut** [comment]
There are other failing tests on Python 3.5.  Maybe if I fix those on posix, Windows may benefit as well.  I really dislike the way green communicates with its subprocesses, but I haven't yet found a better way that works across all versions and platforms without pulling in an external library.

**Comment by CleanCut** [comment]
Did the new release fix anything, by chance?  I'm trying to put together a Windows 10 VM, but if it's already fixed I won't bother...

**Comment by MinchinWeb** [comment]
`green` seems to be working for me now. I never figure out what was the root cause of the issue, so I'm not sure what changed. I guess we can close the issue, and I'll let you know if it starts acting up again. Thanks for taking the time to look into it.

**Comment by CleanCut** [comment]
No problem.  I'm glad it's working for you now!
